# BUILD IMAGE FROM ROOT
# docker build . -f .\session-service\Dockerfile -t session-service 
# Base Build image for multi stage building
FROM golang:1.25.3-alpine AS builder
WORKDIR /session-docker

# Copying only mod files for caching
COPY go.mod go.sum ./
RUN go mod download

# Copying the rest of source code and build binary
COPY session-service/ ./session-service
COPY proto/ ./proto
RUN go build -o main ./session-service/cmd/server 

# Runtime
FROM alpine:3.20
WORKDIR /session-docker

COPY --from=builder /session-docker/main .
COPY /session-service/.env.dev ./session-service/.env.dev

EXPOSE 50055

CMD ["./main"]