// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: gateway/api-gateway.proto

package gatewaypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Types of message status
type MessageStatusType int32

const (
	MessageStatusType_UNKNOWN   MessageStatusType = 0
	MessageStatusType_DELIVERED MessageStatusType = 1
	MessageStatusType_SEEN      MessageStatusType = 2
)

// Enum value maps for MessageStatusType.
var (
	MessageStatusType_name = map[int32]string{
		0: "UNKNOWN",
		1: "DELIVERED",
		2: "SEEN",
	}
	MessageStatusType_value = map[string]int32{
		"UNKNOWN":   0,
		"DELIVERED": 1,
		"SEEN":      2,
	}
)

func (x MessageStatusType) Enum() *MessageStatusType {
	p := new(MessageStatusType)
	*p = x
	return p
}

func (x MessageStatusType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageStatusType) Descriptor() protoreflect.EnumDescriptor {
	return file_gateway_api_gateway_proto_enumTypes[0].Descriptor()
}

func (MessageStatusType) Type() protoreflect.EnumType {
	return &file_gateway_api_gateway_proto_enumTypes[0]
}

func (x MessageStatusType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageStatusType.Descriptor instead.
func (MessageStatusType) EnumDescriptor() ([]byte, []int) {
	return file_gateway_api_gateway_proto_rawDescGZIP(), []int{0}
}

// Chat message from message service
type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // Specijalno za Dervu
	SenderId      string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	RecipientId   string                 `protobuf:"bytes,3,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Body          string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_gateway_api_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_api_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_gateway_api_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ChatMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ChatMessage) GetRecipientId() string {
	if x != nil {
		return x.RecipientId
	}
	return ""
}

func (x *ChatMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ChatMessage) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

// A message status update
type MessageStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	RecipientId   string                 `protobuf:"bytes,2,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	Status        MessageStatusType      `protobuf:"varint,3,opt,name=status,proto3,enum=gateway.MessageStatusType" json:"status,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageStatus) Reset() {
	*x = MessageStatus{}
	mi := &file_gateway_api_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageStatus) ProtoMessage() {}

func (x *MessageStatus) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_api_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageStatus.ProtoReflect.Descriptor instead.
func (*MessageStatus) Descriptor() ([]byte, []int) {
	return file_gateway_api_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *MessageStatus) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageStatus) GetRecipientId() string {
	if x != nil {
		return x.RecipientId
	}
	return ""
}

func (x *MessageStatus) GetStatus() MessageStatusType {
	if x != nil {
		return x.Status
	}
	return MessageStatusType_UNKNOWN
}

func (x *MessageStatus) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Wrapper
type GatewayRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*GatewayRequest_ChatMessage
	//	*GatewayRequest_MessageStatus
	Payload       isGatewayRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayRequest) Reset() {
	*x = GatewayRequest{}
	mi := &file_gateway_api_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayRequest) ProtoMessage() {}

func (x *GatewayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_api_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayRequest.ProtoReflect.Descriptor instead.
func (*GatewayRequest) Descriptor() ([]byte, []int) {
	return file_gateway_api_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *GatewayRequest) GetPayload() isGatewayRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GatewayRequest) GetChatMessage() *ChatMessage {
	if x != nil {
		if x, ok := x.Payload.(*GatewayRequest_ChatMessage); ok {
			return x.ChatMessage
		}
	}
	return nil
}

func (x *GatewayRequest) GetMessageStatus() *MessageStatus {
	if x != nil {
		if x, ok := x.Payload.(*GatewayRequest_MessageStatus); ok {
			return x.MessageStatus
		}
	}
	return nil
}

type isGatewayRequest_Payload interface {
	isGatewayRequest_Payload()
}

type GatewayRequest_ChatMessage struct {
	ChatMessage *ChatMessage `protobuf:"bytes,1,opt,name=chat_message,json=chatMessage,proto3,oneof"`
}

type GatewayRequest_MessageStatus struct {
	MessageStatus *MessageStatus `protobuf:"bytes,2,opt,name=message_status,json=messageStatus,proto3,oneof"`
}

func (*GatewayRequest_ChatMessage) isGatewayRequest_Payload() {}

func (*GatewayRequest_MessageStatus) isGatewayRequest_Payload() {}

// Response, takodje specijalno za Dervu
type GatewayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayResponse) Reset() {
	*x = GatewayResponse{}
	mi := &file_gateway_api_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayResponse) ProtoMessage() {}

func (x *GatewayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_api_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayResponse.ProtoReflect.Descriptor instead.
func (*GatewayResponse) Descriptor() ([]byte, []int) {
	return file_gateway_api_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *GatewayResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GatewayResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_gateway_api_gateway_proto protoreflect.FileDescriptor

const file_gateway_api_gateway_proto_rawDesc = "" +
	"\n" +
	"\x19gateway/api-gateway.proto\x12\agateway\"\x9e\x01\n" +
	"\vChatMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12!\n" +
	"\frecipient_id\x18\x03 \x01(\tR\vrecipientId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\"\xa3\x01\n" +
	"\rMessageStatus\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12!\n" +
	"\frecipient_id\x18\x02 \x01(\tR\vrecipientId\x122\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1a.gateway.MessageStatusTypeR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\x97\x01\n" +
	"\x0eGatewayRequest\x129\n" +
	"\fchat_message\x18\x01 \x01(\v2\x14.gateway.ChatMessageH\x00R\vchatMessage\x12?\n" +
	"\x0emessage_status\x18\x02 \x01(\v2\x16.gateway.MessageStatusH\x00R\rmessageStatusB\t\n" +
	"\apayload\"=\n" +
	"\x0fGatewayResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body*9\n" +
	"\x11MessageStatusType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\r\n" +
	"\tDELIVERED\x10\x01\x12\b\n" +
	"\x04SEEN\x10\x022Q\n" +
	"\x0eGatewayService\x12?\n" +
	"\x06Stream\x12\x17.gateway.GatewayRequest\x1a\x18.gateway.GatewayResponse(\x010\x01B;Z9github.com/Abelova-Grupa/Mercypher/api/external/gatewaypbb\x06proto3"

var (
	file_gateway_api_gateway_proto_rawDescOnce sync.Once
	file_gateway_api_gateway_proto_rawDescData []byte
)

func file_gateway_api_gateway_proto_rawDescGZIP() []byte {
	file_gateway_api_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_api_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_api_gateway_proto_rawDesc), len(file_gateway_api_gateway_proto_rawDesc)))
	})
	return file_gateway_api_gateway_proto_rawDescData
}

var file_gateway_api_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gateway_api_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_gateway_api_gateway_proto_goTypes = []any{
	(MessageStatusType)(0),  // 0: gateway.MessageStatusType
	(*ChatMessage)(nil),     // 1: gateway.ChatMessage
	(*MessageStatus)(nil),   // 2: gateway.MessageStatus
	(*GatewayRequest)(nil),  // 3: gateway.GatewayRequest
	(*GatewayResponse)(nil), // 4: gateway.GatewayResponse
}
var file_gateway_api_gateway_proto_depIdxs = []int32{
	0, // 0: gateway.MessageStatus.status:type_name -> gateway.MessageStatusType
	1, // 1: gateway.GatewayRequest.chat_message:type_name -> gateway.ChatMessage
	2, // 2: gateway.GatewayRequest.message_status:type_name -> gateway.MessageStatus
	3, // 3: gateway.GatewayService.Stream:input_type -> gateway.GatewayRequest
	4, // 4: gateway.GatewayService.Stream:output_type -> gateway.GatewayResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_gateway_api_gateway_proto_init() }
func file_gateway_api_gateway_proto_init() {
	if File_gateway_api_gateway_proto != nil {
		return
	}
	file_gateway_api_gateway_proto_msgTypes[2].OneofWrappers = []any{
		(*GatewayRequest_ChatMessage)(nil),
		(*GatewayRequest_MessageStatus)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_api_gateway_proto_rawDesc), len(file_gateway_api_gateway_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_api_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_api_gateway_proto_depIdxs,
		EnumInfos:         file_gateway_api_gateway_proto_enumTypes,
		MessageInfos:      file_gateway_api_gateway_proto_msgTypes,
	}.Build()
	File_gateway_api_gateway_proto = out.File
	file_gateway_api_gateway_proto_goTypes = nil
	file_gateway_api_gateway_proto_depIdxs = nil
}
