# Base Builder image for multi stage building
FROM golang:1.25.3-alpine AS builder
WORKDIR /message-docker

# Copying only mod files for caching
COPY go.mod go.sum ./
RUN go mod download

# Copying other project content and building the binary
COPY message-service/ ./message-service/
COPY proto/ ./proto/

RUN go build -o main ./message-service/cmd/message-service

FROM alpine:3.20
WORKDIR /message-docker

COPY --from=builder /message-docker/main . 
COPY --from=builder /message-docker/message-service/.env . 

EXPOSE 50052

CMD ["./main"]