# BUILD IMAGE FROM ROOT
#  docker build . -f .\user-service\Dockerfile -t user-service 
# Base Builder image for multi stage building
FROM golang:1.25.3-alpine AS builder
WORKDIR /user-docker

# Copying only mod files for caching
COPY go.mod go.sum ./
RUN go mod download

# Copying other project content and building the binary
COPY user-service/ ./user-service
COPY proto/ ./proto
RUN go build -o main ./user-service/cmd/server

FROM alpine:3.20
WORKDIR /user-docker

COPY  --from=builder /user-docker/main . 
COPY --from=builder /user-docker/user-service/internal/migrations /user-docker/internal/migrations
COPY /user-service/.env.dev ./user-service/.env.dev

EXPOSE 50054

CMD ["./main"]
