// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.1
// source: message/message-service.proto

package messagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message doesn't have an id before passing through MessageService
type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SenderId      string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	RecieverId    string                 `protobuf:"bytes,3,opt,name=reciever_id,json=recieverId,proto3" json:"reciever_id,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_message_message_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_message_message_service_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ChatMessage) GetRecieverId() string {
	if x != nil {
		return x.RecieverId
	}
	return ""
}

func (x *ChatMessage) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *ChatMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type MessageAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageAck) Reset() {
	*x = MessageAck{}
	mi := &file_message_message_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageAck) ProtoMessage() {}

func (x *MessageAck) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageAck.ProtoReflect.Descriptor instead.
func (*MessageAck) Descriptor() ([]byte, []int) {
	return file_message_message_service_proto_rawDescGZIP(), []int{1}
}

func (x *MessageAck) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type MessageRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          int64                  `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"` // obicno ucitavati poslednjih 50 100 itd
	To            int64                  `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageRange) Reset() {
	*x = MessageRange{}
	mi := &file_message_message_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRange) ProtoMessage() {}

func (x *MessageRange) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRange.ProtoReflect.Descriptor instead.
func (*MessageRange) Descriptor() ([]byte, []int) {
	return file_message_message_service_proto_rawDescGZIP(), []int{2}
}

func (x *MessageRange) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *MessageRange) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

type MessageList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageList) Reset() {
	*x = MessageList{}
	mi := &file_message_message_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageList) ProtoMessage() {}

func (x *MessageList) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageList.ProtoReflect.Descriptor instead.
func (*MessageList) Descriptor() ([]byte, []int) {
	return file_message_message_service_proto_rawDescGZIP(), []int{3}
}

func (x *MessageList) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_message_message_service_proto protoreflect.FileDescriptor

const file_message_message_service_proto_rawDesc = "" +
	"\n" +
	"\x1dmessage/message-service.proto\x12\x0fmessage_service\"\x8d\x01\n" +
	"\vChatMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12\x1f\n" +
	"\vreciever_id\x18\x03 \x01(\tR\n" +
	"recieverId\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"+\n" +
	"\n" +
	"MessageAck\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"2\n" +
	"\fMessageRange\x12\x12\n" +
	"\x04from\x18\x01 \x01(\x03R\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\x03R\x02to\"G\n" +
	"\vMessageList\x128\n" +
	"\bmessages\x18\x01 \x03(\v2\x1c.message_service.ChatMessageR\bmessages2\xa6\x01\n" +
	"\x0eMessageService\x12H\n" +
	"\vSendMessage\x12\x1c.message_service.ChatMessage\x1a\x1b.message_service.MessageAck\x12J\n" +
	"\vGetMessages\x12\x1d.message_service.MessageRange\x1a\x1c.message_service.MessageListBGZEgithub.com/Abelova-Grupa/Mercypher/message-service/external/messagepbb\x06proto3"

var (
	file_message_message_service_proto_rawDescOnce sync.Once
	file_message_message_service_proto_rawDescData []byte
)

func file_message_message_service_proto_rawDescGZIP() []byte {
	file_message_message_service_proto_rawDescOnce.Do(func() {
		file_message_message_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_message_service_proto_rawDesc), len(file_message_message_service_proto_rawDesc)))
	})
	return file_message_message_service_proto_rawDescData
}

var file_message_message_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_message_message_service_proto_goTypes = []any{
	(*ChatMessage)(nil),  // 0: message_service.ChatMessage
	(*MessageAck)(nil),   // 1: message_service.MessageAck
	(*MessageRange)(nil), // 2: message_service.MessageRange
	(*MessageList)(nil),  // 3: message_service.MessageList
}
var file_message_message_service_proto_depIdxs = []int32{
	0, // 0: message_service.MessageList.messages:type_name -> message_service.ChatMessage
	0, // 1: message_service.MessageService.SendMessage:input_type -> message_service.ChatMessage
	2, // 2: message_service.MessageService.GetMessages:input_type -> message_service.MessageRange
	1, // 3: message_service.MessageService.SendMessage:output_type -> message_service.MessageAck
	3, // 4: message_service.MessageService.GetMessages:output_type -> message_service.MessageList
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_message_message_service_proto_init() }
func file_message_message_service_proto_init() {
	if File_message_message_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_message_service_proto_rawDesc), len(file_message_message_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_message_message_service_proto_goTypes,
		DependencyIndexes: file_message_message_service_proto_depIdxs,
		MessageInfos:      file_message_message_service_proto_msgTypes,
	}.Build()
	File_message_message_service_proto = out.File
	file_message_message_service_proto_goTypes = nil
	file_message_message_service_proto_depIdxs = nil
}
